### ISSUE TITLE
mvn exec:java does not work in ChoreographyDeployer

### ISSUE THREAD

**Issue by leonardofl** [choreos/choreos_middleware#86]
Probably the problem is related with Rehearsal and SoapUI that depend on a old CXF version.

```
java.lang.IncompatibleClassChangeError: Implementing class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.apache.cxf.bus.extension.Extension.getClassObject(Extension.java:149)
    at org.apache.cxf.bus.extension.ExtensionManagerImpl.activateAllByType(ExtensionManagerImpl.java:137)
    at org.apache.cxf.bus.extension.ExtensionManagerBus.<init>(ExtensionManagerBus.java:131)
    at org.apache.cxf.bus.extension.ExtensionManagerBus.<init>(ExtensionManagerBus.java:139)
    at org.apache.cxf.bus.CXFBusFactory.createBus(CXFBusFactory.java:40)
    at org.apache.cxf.bus.CXFBusFactory.createBus(CXFBusFactory.java:36)
    at org.apache.cxf.bus.CXFBusFactory.createBus(CXFBusFactory.java:32)
    at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:119)
    at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:95)
    at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:69)
    at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:58)
    at org.apache.cxf.BusFactory.getDefaultBus(BusFactory.java:99)
    at org.apache.cxf.BusFactory.createThreadBus(BusFactory.java:165)
    at org.apache.cxf.BusFactory.getThreadDefaultBus(BusFactory.java:155)
    at org.apache.cxf.BusFactory.getThreadDefaultBus(BusFactory.java:140)
    at org.apache.cxf.endpoint.AbstractEndpointFactory.getBus(AbstractEndpointFactory.java:80)
    at org.apache.cxf.jaxrs.AbstractJAXRSFactoryBean.getBus(AbstractJAXRSFactoryBean.java:89)
    at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:138)
    at org.ow2.choreos.rest.RESTServer.run(RESTServer.java:65)
```

**Comment by leonardofl** [comment]
I did some tests, and I found out that maybe the problem is with Linagora's dependencies (easycommons also depends on CXF)...

**Comment by leonardofl** [comment]
Solved by Amleto!

Just added cxf-bundle to the Choreography Deployer pom (on top of dependencies):

a4dbf7448dc5c45355e70d744946b5f3daa408fb
